### ISSUE TITLE
【需求】 方便共享工作区设置

### ISSUE THREAD

**Issue by sagasm** [wecooperate/iMonitorSDK#2]
1. 提供工作区导出功能，或者：
2. 把工作区设置保存在iMonitor安装目录。

**Comment by wecooperate** [comment]
计划中，下个版本支持












iMonitor
***@***.***

人因梦想而伟大

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月9日(周日) 上午9:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitorSDK] 【需求】 方便共享工作区设置 (Issue #2)




  
提供工作区导出功能，或者：
 
把工作区设置保存在iMonitor安装目录。

**Comment by wecooperate** [comment]
计划中，后续版本支持。

目前正在收集常见的工作区，如果有分享的可以发PR合入 https://github.com/wecooperate/iMonitorWorkspace

**Comment by wecooperate** [comment]
需求转到iMonitor，这里是SDK的，关闭issue
