### ISSUE TITLE
无法对Java.exe的修改注册表行为进行拦截

### ISSUE THREAD

**Issue by HPflower** [wecooperate/iMonitorSDK#3]
如题

冰盾版本为2.1.0

再问一下能否增加更多针对注册表的监控模板，比如读取，修改，删除什么的

**Comment by wecooperate** [comment]
高级模式是可以实现修改删除等功能的。
如果操作复杂不方便，可以把需要的功能效果详细描述一下，后面添加对应的模板。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月28日(周三) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitorSDK] 无法对Java.exe的修改注册表行为进行拦截 (Issue #3)




 
如题
 
冰盾版本为2.1.0
 
再问一下能否增加更多针对注册表的监控模板，比如读取，修改，删除什么的

**Comment by HPflower** [comment]
希望后期添加对读取，修改，删除某注册表的模板，最好有弹窗询问用户，让用户来决定阻止/放行/直接终止动作发起的进程。

**Comment by wecooperate** [comment]
读取、修改、删除注册表的模板已经支持。

弹框在计划中，后续版本会支持的。

**Comment by wecooperate** [comment]
请更新到2.2.0版本

**Comment by wecooperate** [comment]
iDefender的相关问题请后续到 https://github.com/wecooperate/iDefender/issues 这边发起，这里先关闭
