### ISSUE TITLE
win11 安装好后打开报错灾难性故障

### ISSUE THREAD

**Issue by w990222** [wecooperate/iMonitorSDK#4]
![image](https://github.com/user-attachments/assets/4b42ab2e-43a6-454f-b4c7-e8d41782da85)
win11 安装好后打开报错灾难性故障

**Comment by wecooperate** [comment]
驱动加载被其他安全软件拦截导致，自己处理加白



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 上午9:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iMonitorSDK] win11 安装好后打开报错灾难性故障 (Issue #4)




 
image.png (view on web)
 win11 安装好后打开报错灾难性故障

**Comment by w990222** [comment]
要管理员权限才能运行
